
spring:
  application:
    name: project
  datasource:
    password: 572114
    url: jdbc:postgresql://localhost:5432/antivirus_db
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update


jwt:
  secret: "Walkermoon"
  expiration: 3600000 # 1 hour in milliseconds


